### ISSUE TITLE
whythere is not a independent SFE_MicroOLED.cpp 

### ISSUE THREAD

**Issue by watershade** [micooke/sparkfun_OLED#1]
I find you have move the codes in SFE_MicroOLED.cpp to SFE_MicroOLED.h
I want to know why? 
Sorry, it is not a issue

**Comment by micooke** [comment]
Anything in a cpp is compiled separately, then linked into the arduino project.
If you keep it header only, or keep the configurable bits in the header, it means you can change the configuration at compile time in your ino file, rather than having to change the library for each project.

**Comment by micooke** [comment]
Anything in an #ifdef or #if guard  gets evaluated to its state from the header if the guards are in a cpp.

**Comment by watershade** [comment]
Thanks. It is a smart way even I don't think it is a good mothod to deal with this situation.
I'll close this comment. Thanks for your reply.

**Comment by micooke** [comment]
You don't think making a library compile time configurable and reducing compiled code space for a microcontroller is a good method? Pray tell what a better method is, and why exactly you think this is bad.
